# Generated by Django 6.0.6 on 2026-07-29 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='ats_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
