# Generated by Django 6.0.6 on 2026-08-04 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_flagged'),
        ('core', '0010_job_core_job_status_4b2344_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['status'], name='core_applic_status_148db8_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['candidate'], name='core_applic_candida_43c5dc_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['job'], name='core_applic_job_id_0e9ae8_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['applied_at'], name='core_applic_applied_8f6560_idx'),
        ),
    ]
