# Generated by Django 6.0.6 on 2026-09-10 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_application_core_applic_status_148db8_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='ai_call_status',
            field=models.CharField(blank=True, choices=[('QUEUED', 'Queued'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], max_length=20, null=True),
        ),
    ]
