# Generated by Django 6.0.6 on 2026-09-10 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_application_ai_call_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='ai_call_scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
