# Generated by Django 6.0.6 on 2026-09-10 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_flagged'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='is_available_for_ai_call',
            field=models.BooleanField(default=True),
        ),
    ]
