ROLES = [
    "software engineer",
    "software developer",
    "full stack developer",
    "frontend developer",
    "backend developer",
    "python developer",
    "django developer",
    "react developer",
    "java developer",
    "web developer",
    "mobile developer",
    "android developer",
    "ios developer",
    "devops engineer",
    "cloud engineer",
    "data analyst",
    "data scientist",
    "machine learning engineer",
    "ai engineer",
    "qa engineer",
    "test engineer",
    "system administrator",
    "network engineer",
    "database administrator",
    "project manager",
    "technical lead",
    "intern",
]