SKILLS = [
    "python",
    "java",
    "c",
    "c++",
    "c#",
    "javascript",
    "typescript",
    "html",
    "css",
    "react",
    "angular",
    "vue",
    "django",
    "flask",
    "fastapi",
    "node.js",
    "express",
    "mongodb",
    "mysql",
    "postgresql",
    "sqlite",
    "firebase",
    "git",
    "github",
    "docker",
    "kubernetes",
    "aws",
    "azure",
    "rest api",
    "graphql",
    "redis",
    "linux",
    "bootstrap",
    "tailwind css",
    "figma",
    "postman",
    "jira",
    "numpy",
    "pandas",
    "tensorflow",
    "pytorch",
    "machine learning",
    "artificial intelligence",
    "data structures",
    "algorithms",
]